coverage:
  status:
    project:
      default:
        informational: false
    patch:
      default:
        informational: false

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: true
